import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import TopBar from "../components/TopBar";
import { acceptInvitation, declineInvitation, listInvitations, listNotifications, markAllNotificationsRead, markNotificationRead } from "../api/collaboration";
import { extractErrorMessage } from "../api/client";
import { getInitials, notificationInitials, timeAgo } from "../utils/decisionHelpers";

export default function Notifications() {
  const [items, setItems] = useState([]); const [invitations, setInvitations] = useState([]); const [error, setError] = useState("");
  useEffect(() => { Promise.all([listNotifications(), listInvitations()]).then(([notifications, pending]) => { setItems(notifications.data); setInvitations(pending.data); }).catch((err) => setError(extractErrorMessage(err, "Couldn't load notifications"))); }, []);
  const read = async (item) => { if (!item.read) { const { data } = await markNotificationRead(item.id); setItems((all) => all.map((entry) => entry.id === item.id ? data : entry)); window.dispatchEvent(new Event("decisionhub:notifications-changed")); } };
  const readAll = async () => { try { await markAllNotificationsRead(); setItems((all) => all.map((item) => ({ ...item, read: true }))); window.dispatchEvent(new Event("decisionhub:notifications-changed")); } catch (err) { setError(extractErrorMessage(err, "Couldn't mark notifications as read")); } };
  const respondToInvitation = async (invitation, action) => { try { if (action === "accept") await acceptInvitation(invitation.id); else await declineInvitation(invitation.id); setInvitations((all) => all.filter((item) => item.id !== invitation.id)); } catch (err) { setError(extractErrorMessage(err, "Couldn't update invitation")); } };
  return <div><TopBar eyebrow="Stay in the loop" title="Notifications" subtitle="Updates from the decisions and conversations you follow." action={items.some((item) => !item.read) ? <button className="btn ghost" onClick={readAll}>Mark all read</button> : null} />{error && <div className="error-banner">{error}</div>}{invitations.length > 0 && <section className="panel invitation-panel"><div className="section-head"><div><span className="eyebrow">Community access</span><h2>Invitations</h2></div><span>{invitations.length} pending</span></div>{invitations.map((invitation) => { const inviterName = invitation.inviter?.name || invitation.community?.owner?.name || "Community owner"; return <div className="invitation-row" key={invitation.id}><div className="invitation-user"><div className="avatar notification-avatar" aria-hidden="true">{getInitials(inviterName)}</div><div><strong>{invitation.community?.name || "Community"}</strong><p>Invited by {inviterName}</p></div></div><div className="detail-actions"><button className="btn ghost" onClick={() => respondToInvitation(invitation, "decline")}>Decline</button><button className="btn brass" onClick={() => respondToInvitation(invitation, "accept")}>Accept</button></div></div>; })}</section>}{items.length === 0 && invitations.length === 0 ? <div className="state-block"><h3>You’re all caught up</h3><p>Votes, comments, and community invitations will show up here.</p></div> : items.length > 0 && <div className="panel"><div className="recent-boards">{items.map((item) => <Link key={item.id} className="recent-board-row notification-row" to={item.decisionId ? `/boards/${item.decisionId}` : "/dashboard"} onClick={() => read(item)}><span className={`recent-status ${item.read ? "closed" : "open"}`} /><div className="avatar notification-avatar" aria-hidden="true">{notificationInitials(item)}</div><div className="recent-main"><h3>{item.message}</h3><p>{(item.type || "general").toLowerCase()} <span>·</span> {timeAgo(item.createdAt)}</p></div><span className="recent-arrow">→</span></Link>)}</div></div>}</div>;
}
